### ISSUE TITLE
Peer-Peer Code Review: Module-II (Week 2)

### ISSUE THREAD

**Issue by fasaldana** [RaoAkif/TodoList#2]
### To take note 📝
Clean code, organized and everything's working fine.
- Kindly add a build property inside your package.json file with the required command to build your web page.
- You should install webpack serve dependencies inside your project and add the following command inside the scripts property on your package.json file: "start": "webpack serve --open", with that it will fix the problem with starting the server.

**Comment by RaoAkif** [comment]
Added the Webpack Dev Server to the package.json
